### ISSUE TITLE
行操作中自定义dialog如何传入当前行的数据呢？

### ISSUE THREAD

**Issue by lijiuhui** [lphkxd/hyperf-admin#15]
我需要在自定义dialog中传入当前行的数据，比如id，提交表单时候把这个id和表单数据一起提交到指定actions。请问应当调用哪个接口呢？目前我是通过item来实现的。这样会把id显示出来，不是很好。

谢谢。

**Comment by lphkxd** [comment]
系统内置的后端用法是使用 $form->getResourceId() 获取当前修改的资源ID ，不用写在表单内，id是通过path参数传递的
