### ISSUE TITLE
有个问题问一下,接口的效率貌似不是很高. 跟我纯hyperf的效率差距挺大的.不知道是哪里的问题?

### ISSUE THREAD

**Issue by jonny77** [lphkxd/hyperf-admin#19]
![WX20210902-211301](https://user-images.githubusercontent.com/1962170/131849822-c2c0b369-da75-4689-afde-120a717805ba.png)
数据库数据非常少 < 100条. 我用hyperf原生写的接口大约10ms左右....担心后面数据多起来之后,效率会不会更低......

**Comment by xiaoweipeng** [comment]
jwt驱动的问题

**Comment by lphkxd** [comment]
尽量不在action里写sql 多用关联查询

**Comment by jonny77** [comment]
> 尽量不在action里写sql 多用关联查询

实际上并没有写sql.

**Comment by lphkxd** [comment]
鉴权认证之类的都有吗，随便带点业务100毫秒左右了正常
