### ISSUE TITLE
麻烦问一下这个怎么用啊？

### ISSUE THREAD

**Issue by KJohn2q** [lphkxd/hyperf-admin#2]
您好

我在本地部署了该项目，并不能按我想要的方式工作，readme文档中也没有明确的指示

希望得到您的回答

**Comment by great-zh** [comment]
> 您好
> 
> 我在本地部署了该项目，并不能按我想要的方式工作，readme文档中也没有明确的指示
> 
> 希望得到您的回答

你好。该项目我重构了。按照hyperf标准的写法重构，目前已完成用户、文章、菜单、权限管理，这两天会重新发布一个版本。 这个版本太多tp遗留的问题。

**Comment by KJohn2q** [comment]
好的 谢谢  期待新的版本

**Comment by lphkxd** [comment]
> 好的 谢谢 期待新的版本
新地址
https://github.com/lphkxd/hyperf-admin
