### ISSUE TITLE
与最新版本不兼容了，up主用的是哪个版本的呢？报错信息如下

### ISSUE THREAD

**Issue by super179** [lphkxd/hyperf-admin#24]
Problem 1
    - hyperf-plus/admin[v2.0.1, ..., v2.0.3] require hyperf-plus/ui ^1.0.0 -> satisfiable by hyperf-plus/ui[v1.0.7, ..., v1.x-dev].
    - hyperf-plus/admin[v2.0.4, ..., v2.1.3] require hyperf/model-cache ^2.0.0 -> satisfiable by hyperf/model-cache[v2.0.0, ..., 2.2.x-dev].
    - hyperf-plus/admin dev-old requires hyperf/cache ~1.1.0 -> found hyperf/cache[v1.1.0, ..., 1.1.x-dev] but it conflicts with your root composer.json require (~3.1.0).
    - hyperf-plus/admin dev-v3-develop requires hyperf-plus/ui ^3.1 -> found hyperf-plus/ui[dev-luoxin, dev-v3-develop, v1.0.7, ..., v1.x-dev] but it does not match the constraint.
    - hyperf-plus/admin[v0.1.0, ..., v0.1.3] require hyperf/command ~2.0.0 -> found hyperf/command[v2.0.0, ..., 2.0.x-dev] but it conflicts with your root composer.json require (~3.1.0).
    - hyperf-plus/admin[v2.2, ..., v2.x-dev] require hyperf/redis ^2.0.0 -> found hyperf/redis[v2.0.0, ..., 2.2.x-dev] but it conflicts with your root composer.json require (~3.1.0).
    - hyperf-plus/ui[v1.0.7, ..., v1.0.31] require hyperf/http-message ~2.0.0 -> found hyperf/http-message[v2.0.0, ..., 2.0.x-dev] but these were not loaded, likely because it conflicts with another require.
    - hyperf-plus/ui[v1.0.32, ..., v1.0.53] require hyperf/http-message ^2.0 -> found hyperf/http-message[v2.0.0, ..., 2.2.x-dev] but these were not loaded, likely because it conflicts with another require.
    - hyperf/model-cache[v2.0.0, ..., 2.0.x-dev] require hyperf/contract ~2.0.0 -> found hyperf/contract[v2.0.0, ..., 2.0.x-dev] but these were not loaded, likely because it conflicts with another require.
    - hyperf/model-cache[v2.1.0-beta1, ..., 2.1.x-dev] require hyperf/contract ~2.1.0 -> found hyperf/contract[v2.1.0-beta1, ..., 2.1.x-dev] but these were not loaded, likely because it conflicts with another require.
    - hyperf/model-cache[v2.2.0-beta1, ..., 2.2.x-dev] require hyperf/contract ~2.2.0 -> found hyperf/contract[v2.2.0-beta1, ..., 2.2.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires hyperf-plus/admin * -> satisfiable by hyperf-plus/admin[dev-old, dev-v3-develop, v0.1.0, v0.1.1, v0.1.2, v0.1.3, v2.0.1, ..., v2.x-dev].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require hyperf-plus/admin:*" to figure out if any version is installable, or "composer require hyperf-plus/admin:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by lphkxd** [comment]
v3的还没正式发布，v2.x的目前是最新的
