### ISSUE TITLE
菜单收缩后，二级菜单的hover显示成黑色，看不到菜单文字

### ISSUE THREAD

**Issue by justmd5** [lphkxd/hyperf-admin#8]
![image](https://user-images.githubusercontent.com/4120960/103856928-73cb2b80-50f0-11eb-9abd-3a3fe12b8179.png)

**Comment by lphkxd** [comment]
已更新，使用composer update 最新至更新版本，然后执行 php bin/hyperf.php ui:update 进行UI资源文件升级
